### PR TITLE
Excalidraw updated to latest 0.11.0

### PR DESCRIPTION
**Pull request by hero101**
### Describe the background of your pull request

- I did not find any regressions
- a breaking change was introduced when serializing to json in order for the canvas content to be saved, which was easily fixed
- Source maps are not fixed - I am not aware if this is an issue for us
- Library imports work correctly
## New features from the patch notes

> - images support
> - hyperlink support
> - initialData object now supports additional files (BinaryFiles) attribute.
> - Export THEME constant from the package so host can use this when passing the theme
> - added getFiles() to get current BinaryFiles (Record<FileId, BinaryFileData>). 

**There is one concerning thing from the last point which I don't know how should be handled**
> getFiles() may contain files that aren't referenced by any element, so if you're persisting the files to a storage, you should compare them against stored elements.

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Comment by Comoque1** [comment]
Deployed on TEST env and overall works fine.
The only issue happens, when try to save as png/svg, errors are thrown in the browser console.
image

**Comment by Comoque1** [comment]
The issue described above was on DEV env. Not reproducible on TEST, which contains this changes. So, no comments to be addressed :)

**Comment by techsmyth** [comment]
Great that this is working! What are the implications regarding our storage space allocation for Canvases from now also storing files? This may need a broader discussion.

**Comment by hero101** [comment]
> Great that this is working! What are the implications regarding our storage space allocation for Canvases from now also storing files? This may need a broader discussion.

@techsmyth They are encoded in base64 when saved.

**Review by valentinyanakiev — APPROVED** [review]

**Comment by Comoque1** [comment]
> Great that this is working! What are the implications regarding our storage space allocation for Canvases from now also storing files? This may need a broader discussion.

Quite valid point! Raised an [issue](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1756) for discussion.

**Pull request merged**
