### PR TITLE
updated to work with application creation api for preserving order

### PR DESCRIPTION
**Pull request by techsmyth**
This PR works agains the server PR with the same number: https://github.com/alkem-io/server/pull/1429

This works against the updated server version, but does not actually send back up the sort order from the template. That is marked as a todo in the ApplyPage function.

### CODE REVIEW

**Review by techsmyth — COMMENTED** [review]
Working nice with order preserved...

**Review by atstoyanov — APPROVED** [review]

**Comment by valentinyanakiev** [comment]
Creating an application on dev:
Variable "$input" got invalid value { name: "What makes you want to join?", value: "123" } at "input.questions[0]"; Field "sortOrder" of required type "Float!" was not provided.

**Comment by techsmyth** [comment]
Looks like the latest version of the client is not deployed?

**Pull request merged**
