### PR TITLE
User profile page - alignment issues

### PR DESCRIPTION
**Pull request by hero101**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Comment by hero101** [comment]
Issue seems to be resolved by [#644](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/644)
- Used the core Tag components instead of what was already there.

**Review by techsmyth — APPROVED** [review]
The tags height is showing up better, so the actually defined issue is solved. 

However I notice that the display is not cropped, so if there are long / many tags they spill over:

image

**Comment by hero101** [comment]
@techsmyth I suspect you are not using the code from the branch, since I replaced the code for the tags, and the theming is different - image for reference

image

**Review by techsmyth — APPROVED** [review]
Indeed, just refreshed again and it is showing the new look + feel, working nicely...

**Pull request merged**
