### PR TITLE
Templates tags fix

### PR DESCRIPTION
**Pull request by alstojanovic**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Review by valentinyanakiev — CHANGES_REQUESTED** [review]
The solution doesn't fix the bugs. When updating tagsets, `tagsetId` remains undefined:

image

**Comment by valentinyanakiev** [comment]
{
  "errors": [
    {
      "message": "Variable \"$profile\" got invalid value { tags: [\"test\", \"test1\"] } at \"profile.tagsets[0]\"; Field \"ID\" of required type \"UUID!\" was not provided.",
      "locations": [
        {
          "line": 1,
          "column": 82
        }
      ],
      "extensions": {
        "code": "BAD_USER_INPUT",
        "exception": {
          "stacktrace": [
            "GraphQLError: Variable \"$profile\" got invalid value { tags: [\"test\", \"test1\"] } at \"profile.tagsets[0]\"; Field \"ID\" of required type \"UUID!\" was not provided.",
            "    at /home/valentin/source/repos/alkemio/server/node_modules/graphql/execution/values.js:116:15",
            "    at coerceInputValueImpl (/home/valentin/source/repos/alkemio/server/node_modules/graphql/utilities/coerceInputValue.js:99:11)",
            "    at coerceInputValueImpl (/home/valentin/source/repos/alkemio/server/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
            "    at /home/valentin/source/repos/alkemio/server/node_modules/graphql/utilities/coerceInputValue.js:70:14",
            "    at Array.map (<anonymous>)",
            "    at safeArrayFrom (/home/valentin/source/repos/alkemio/server/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
            "    at coerceInputValueImpl (/home/valentin/source/repos/alkemio/server/node_modules/graphql/utilities/coerceInputValue.js:68:50)",
            "    at coerceInputValueImpl (/home/valentin/source/repos/alkemio/server/node_modules/graphql/utilities/coerceInputValue.js:105:34)",
            "    at coerceInputValue (/home/valentin/source/repos/alkemio/server/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
            "    at _loop (/home/valentin/source/repos/alkemio/server/node_modules/graphql/execution/values.js:109:69)",
            "    at coerceVariableValues (/home/valentin/source/repos/alkemio/server/node_modules/graphql/execution/values.js:121:16)",
            "    at getVariableValues (/home/valentin/source/repos/alkemio/server/node_modules/graphql/execution/values.js:50:19)",
            "    at buildExecutionContext (/home/valentin/source/repos/alkemio/server/node_modules/graphql/execution/execute.js:203:61)",
            "    at executeImpl (/home/valentin/source/repos/alkemio/server/node_modules/graphql/execution/execute.js:101:20)",
            "    at execute (/home/valentin/source/repos/alkemio/server/node_modules/graphql/execution/execute.js:60:35)",
            "    at execute (/home/valentin/source/repos/alkemio/server/node_modules/apollo-server-core/src/requestPipeline.ts:501:34)"
          ]
        }
      }
    }
  ]
}

**Comment by alstojanovic** [comment]
The error should be fixed with the last commit. Please check if you have the latest branch.

**Comment by alstojanovic** [comment]
Fix is pushed for all template types.

**Review by valentinyanakiev — APPROVED** [review]

**Pull request merged**
