### PR TITLE
Tidy up env variables

### PR DESCRIPTION
**Pull request by atstojanov**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Review by techsmyth — COMMENTED** [review]
This PR is good to go, fixes some legacy code.

However it is only a small part of the overall issue. What is the plan for the other items?

**Comment by atstojanov** [comment]
> This PR is good to go, fixes some legacy code.
> 
> However it is only a small part of the overall issue. What is the plan for the other items?

They are still in use. The Sentry configuration can be moved to the server rest of the variables are just for build information and is normal to have them. The graphql endpoint can be preserved for development purposes, which is quite unlikely to be used.

Also the [aws-amplify deployment](https://create-react-app.dev/docs/deployment#aws-amplify) worth a try.

**Comment by techsmyth** [comment]
OK, so we need to then extend the server to hold the sentry config, that would logically fit there. Will raise a separate issue for that. 

There are a couple of odd ones still in the .env.docker:
image

And regarding the .env file, is that only used for the .env.deployment script or does it also get picked up at runtime?

Finally, we should move the .env.deployment folder in under the .build folder, as it looks to be only part of the build - right?

Is the .env.production still needed?

The whole setup just feels too complicated, lots of environment variables + different usages.

**Comment by techsmyth** [comment]
Just reflecting on this some more, I do think we need to keep the GRAPHQL_ENDPOINT env var. Sorry, missed its full usage this morning. The .env.production file can stay deleted. 

Otherwise follow up changes look good.

**Review by techsmyth — APPROVED** [review]
Looks good; nice to have this cleaner.

**Pull request merged**
