### PR TITLE
Create Template in Subspace settings - check for parent space permissions

### PR DESCRIPTION
**Pull request by bobbykolev**
https://github.com/alkem-io/client-web/issues/7151

To solve the issue I used the **Update** permission on the parent space.
The spaceId was not available so I passed it from where we're gathering the journeyId.
There are two separate button components based on the premission because in a disabled state the Tooltip is not triggered.

## Summary by CodeRabbit

- **New Features**
	- Added community engagement sections and updated footer links for improved navigation.
	- Enhanced template management in Space Settings, including user privilege checks for creating templates.
	- Improved accessibility with updated alt text for visuals and additional validation messages in forms.

- **Bug Fixes**
	- Refined user-facing messages in authentication and error display sections for clarity.

- **Documentation**
	- Updated strings and sections in the translation files to enhance user experience across the platform.

### CODE REVIEW

**Comment by techsmyth** [comment]
@bobbykolev another thought: every space can access the templatesManager & then the templates set in that. So possible to check for create directly on the templatesSet? Would also avoid need to pass around parent space id…

**Comment by bobbykolev** [comment]
> @bobbykolev another thought: every space can access the templatesManager & then the templates set in that. So possible to check for create directly on the templatesSet? Would also avoid need to pass around parent space id…

@techsmyth , I can't quite understand your suggestion. 
We are trying to create the template in the templateSet and the fix is to catch it before trying to. Is there another privilege or you are suggesting something else?

**Comment by techsmyth** [comment]
If you are planning to create the template, then you need to have the templatesSet ID. So why not just do a check for the CREATE privilege on the TemplatesSet entity? And second point is that you can easily get to the templatesSet directly from any space via the TemplatesManager.

**Comment by bobbykolev** [comment]
> If you are planning to create the template, then you need to have the templatesSet ID. So why not just do a check for the CREATE privilege on the TemplatesSet entity? And second point is that you can easily get to the templatesSet directly from any space via the TemplatesManager.

Got it. It makes sense to check that instead of 'Update' on space, thanks!

**Review by ccanos — APPROVED** [review]

**Pull request merged**
