### PR TITLE
Creation of aspects

### PR DESCRIPTION
**Pull request by hero101**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Review by techsmyth — DISMISSED** [review]
Core flow is working nicely for me. Only issue I saw is that the label for related_initiative is not showing up.

Some labels etc can be adjusted after functional path is finished. 

Two other usability points now that I see it:
- it would be nice to give help icons to explain the different fields
- the nameID input box should have some validation to check the length, characters used etc
I will raise these in a separate issue for refining the user experience.

**Review by techsmyth — COMMENTED** [review]
Trying to go to the context tab as a not logged in user triggers the following error:
image

**Comment by hero101** [comment]
> Trying to go to the context tab as a not logged in user triggers the following error: image

That happens because the context authorization and the fields in it are queried at the same time.
In order to avoid this error I can:
- Do two queries: one for context auth and one for aspects and references
- Continue using one query and avoid showing the errors - sections can be hidden based on the read priviliges.

**Comment by Comoque1** [comment]
When creating "Aspect" using the client, display name is sent for both fields `displayName` and `nameId`.
image

**Review by Comoque1 — APPROVED** [review]

**Pull request merged**
