### PR TITLE
Tags on Cards don't expand beyond 2 rows.

### PR DESCRIPTION
**Pull request by me-andre**
### Describe the background of your pull request

Created LinesFitter component that prevents a flex (row-wrap) container from growing beyond its initial height
by limiting the number of child nodes.
It can be conditionally applied to various flex containers, currently enabled in `TagsComponent`.

Fixes: BUG: Cards to have the same fixed height

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Review by techsmyth — APPROVED** [review]
Working very nicely for me :)

**Comment by hero101** [comment]
- The card is wider than the rest
image
- Cards have different dimensions. Even the empty tag containers have weird heights.
image

**Review by hero101 — CHANGES_REQUESTED** [review]
- The card is wider than the rest
image
- Cards have different dimensions. Even the empty tag containers have weird heights.
image

**Comment by me-andre** [comment]
@hero101 , thanks for the cases. I think they are mostly styling issues, I'm going address them now.

**Comment by me-andre** [comment]
@hero101 , the issues are fixed.

**Pull request merged**
